apiVersion: v1
kind: ConfigMap
metadata:
  name: cumberland-certs
  namespace: validator
data:
  cumberland-1.pem: |
    -----BEGIN CERTIFICATE-----
    MIIDbzCCAlegAwIBAgIQHwr0GrBdEyBoIMmPDtEeyzANBgkqhkiG9w0BAQsFADBL
    MRAwDgYDVQQKEwdBY21lIENvMTcwNQYDVQQDEy5LdWJlcm5ldGVzIEluZ3Jlc3Mg
    Q29udHJvbGxlciBGYWtlIENlcnRpZmljYXRlMB4XDTI2MDMwNTIzMDcwMVoXDTI3
    MDMwNTIzMDcwMVowSzEQMA4GA1UEChMHQWNtZSBDbzE3MDUGA1UEAxMuS3ViZXJu
    ZXRlcyBJbmdyZXNzIENvbnRyb2xsZXIgRmFrZSBDZXJ0aWZpY2F0ZTCCASIwDQYJ
    KoZIhvcNAQEBBQADggEPADCCAQoCggEBAOApUAGss4VCBUN7GtTPI+yuxVghM5U8
    5dwfgcqDVueF8Pdtd9mDi1pAh11OJBKDiInNgE/GLLg+5mWI38ZB5BFhnDgLgQl8
    Wabz67WdzwiiL6TwNNkZKF83ouNDo2cA52orb+QVxT6J5hUs6Ye/3KrmIkhihrPD
    WievY8fI4MsMGkqUMeEhPCelU86+g3YI+VMl4mufsGnUPNUmKSEf3V69TzS8SqlF
    KduC2+0FhQWHbtqc2kyFY+brGJIctzHdysTl/Oyy2dbu8fxeS1G1XGTQFZxcsFZ7
    gjUOUQ8JHngaSOfPPbYsX895LLXVyGbFyqHJBgxd3UUHxyUkWUGuBIkCAwEAAaNP
    ME0wDgYDVR0PAQH/BAQDAgWgMBMGA1UdJQQMMAoGCCsGAQUFBwMBMAwGA1UdEwEB
    /wQCMAAwGAYDVR0RBBEwD4INaW5ncmVzcy5sb2NhbDANBgkqhkiG9w0BAQsFAAOC
    AQEArxORYe6xjoVtQ8fjwK2tpKssj/zhL3ySnU3307FtXuqEd3gpEAZ9CpeQzKPQ
    Yv/F2FgTbnh/N9YAO4DKuTUcFQfOBCaKHjt6b2bmKmTYDj6UjKOeIemm32s0UrX9
    Yf81QjLHipHpM6CT05V++trNq/NlrYl0CjrgsUdevoKJoGlGDNv4FSHza9hdZoWp
    5bFc2EtaQe3XZLCnxVFaxJ+MWjFkxI23CKAY3T2UGemoFparSqpMqfvLrsX4wxx8
    Y6389sZt3w8sgxuZftt1CDwHujarKe/JpsLZu3TJM2St7caNmrjFhBAsERBFNVCS
    M18TM4QcGqZpgB6cNHWt7u0Fkg==
    -----END CERTIFICATE-----
  cumberland-2.pem: |
    -----BEGIN CERTIFICATE-----
    MIIDbzCCAlegAwIBAgIQCUobErCkzqO1XTZvE8GQcDANBgkqhkiG9w0BAQsFADBL
    MRAwDgYDVQQKEwdBY21lIENvMTcwNQYDVQQDEy5LdWJlcm5ldGVzIEluZ3Jlc3Mg
    Q29udHJvbGxlciBGYWtlIENlcnRpZmljYXRlMB4XDTI2MDMwNTIzMTQ0NloXDTI3
    MDMwNTIzMTQ0NlowSzEQMA4GA1UEChMHQWNtZSBDbzE3MDUGA1UEAxMuS3ViZXJu
    ZXRlcyBJbmdyZXNzIENvbnRyb2xsZXIgRmFrZSBDZXJ0aWZpY2F0ZTCCASIwDQYJ
    KoZIhvcNAQEBBQADggEPADCCAQoCggEBANdoIvd99FwK9CLtqIqBX5fcADwJSJaM
    IBeO9LNkFlwYck1ggVYsUxpSFZhglPujvNq0jqmyUS5vV7nsZF7L3mzIZ0ImJcw7
    L6tlovy7XMe2Ulin/JPkm5ArmESCMOBr5rrK+qqGUxZGNhHQRmEkIf+Jbk/p5Cv5
    hNeK7lxEgPguNiifXSJETw0roEPazLbbIwRMFi9t4r13T9A6OxaLDZmUJc3cktLS
    G7CNp1WNUE41gM1cxxsy9jehyguDavLXeGjkKG30vaCusAHvC4QXiSDK6/HbjFVg
    UezmZhrEdY4GJ/t4BZ05wrLyZd76SxN4g3z7/hzK/wCY1chRK9QtLe8CAwEAAaNP
    ME0wDgYDVR0PAQH/BAQDAgWgMBMGA1UdJQQMMAoGCCsGAQUFBwMBMAwGA1UdEwEB
    /wQCMAAwGAYDVR0RBBEwD4INaW5ncmVzcy5sb2NhbDANBgkqhkiG9w0BAQsFAAOC
    AQEAbqVehYtb57cjAsgvq45AdT9ztQBXAcyBxQf+sFQvwlXKO+LHgEDL9pDeDMP2
    cdfabBtBMLyiIbWUAsvqeSaAqK2LYlkpw9CURflfqdk7k4icO2xcQObGSvgL1Fq0
    pNIA5+D6NO2JbzFljyrF4VpbRqvSVBBP3cyGCXpKYv7ZJ5WuhDfklLbbDyqnrnco
    ydVDfvuyERNDH3SHsV2EfatbqebUSmHZ7O4E9uGFMnglc9BnUzprqP4Ru8MJG9Ea
    3b4w9ZeFi8Id/JW9fnQhOwssjLY/+7DGUtV4+UWVjJuPAUNUbCBhVt1+ZPFfxDE/
    6/WHqmsB6vnPFMV9IuTpET5j7w==
    -----END CERTIFICATE-----
